version: '3'

services:
  db:
    image: "postgres:latest"
    env_file: .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: vinta
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    env_file: .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A githubmonitor worker --loglevel=info
    volumes:
      - .:/app/
    env_file: .env
    depends_on:
      - db
      - redis

  webpack:
    build:
      context: .
      dockerfile: Dockerfile-webpack
    command: npm run dev
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - .:/app/
      - /app/node_modules

  redis:
    image: "redis:latest"
